### ISSUE TITLE
Chart.yaml includes keywords mapped to OpenShift categories

### ISSUE THREAD

**Issue by baijum** [redhat-certification/chart-verifier#39] opened 2021-03-08 11:56 UTC
ref. https://issues.redhat.com/browse/HELM-107

**Comment by komish** [comment] 2023-01-27 21:07
@mmulholla I can't determine what the next action would be here. Would recommend **closing** based on the age.

**Comment by komish** [comment] 2023-04-13 14:32
Closing at this time. The issue is stale, and does not contain enough detail capturing the desired outcome.

**Closed by komish** 2023-04-13 14:32 UTC
Labels: chart-checks
