### ISSUE TITLE
Output goes to stderr instead of stdout

### ISSUE THREAD

**Issue by tetchel** [redhat-certification/chart-verifier#208] opened 2021-10-19 19:02 UTC
Even when 'verify' runs successfully, the output goes to stderr. This is not expected, especially given that the user has to do the redirection themselves without https://github.com/redhat-certification/chart-verifier/issues/207

**Comment by mmulholla** [comment] 2022-01-10 15:27
From experimentation all we need to do is add this before generating output:
```
cmd.SetOutput(os.Stdout)
```

However this would be quite a change affecting all existing use that are specify ```2>report.yam```

**Comment by komish** [comment] 2023-01-27 16:02
@mmulholla I think this is also a duplicate of #117 #123 and should be **good to close**.

**Comment by komish** [comment] 2023-03-02 20:20
Closing, in my testing some log output goes to stderr but the report goes to stdout.

**Closed by komish** 2023-03-02 20:20 UTC
